### PR TITLE
 EPMCUXDA-6483: backend project structure: Update build flow

### PR DESCRIPTION
**Pull request by mishelen**
1. instead `eslint-config-airbnb` with additional react-based dependencies (`...-react` + `...jsx-a11y`) was used `eslint-config-airbnb-base`-- which appropriate for server-side.
2. removed all direct calls to packages executables (node_modules/.bin/exe)
3. added cross-env package to define env variables on all OS types
4. changed npm scripts:
    - `start` used  by many systems as default command to run production ready build, so
    - old `start` became `start:dev`
    - added `rimraf` to clean build artifacts
5. updated `tsconfig`
    - `"target": "es2017"` (`es6` (same as `es2016`) it's probably too old)
    - `"allowSyntheticDefaultImports": true`, allows to get rid of asterisks in `import * as lodash from 'lodash'`, very handy
    - other rules....
6. removed `tslint` & `ts-node` as unused
7. most of files was prettified

### CODE REVIEW

**Comment by Shutya** [comment]
Misha, thank you. Can we use `morgan` for logging requests and `helmet` for security?

**Comment by fyrku** [comment]
👍

**Comment by dzmitrypanamarenka** [comment]
Thanks for adding)
But what's wrong with direct calls to packages? We don't need globals in this case

**Comment by dzmitrypanamarenka** [comment]
> Misha, thank you. Can we use `morgan` for logging requests and `helmet` for security?

We're waiting for PR which adds logger. Also we have a guy who's working at adding Helmet

**Comment by mishelen** [comment]
Regarding loggin tools, ofcourse we need `morgan`, but we need `winston` or `bunyan` too

@dzmitrypanamarenka please clarify, what exactly your guys want to add, to @Shutya be able and to know can he collaborate on loggers topic

**Comment by mishelen** [comment]
>  But what's wrong with direct calls to packages? We don't need globals in this case
In this case it should be done in way: 

```json
{
"tsc": "tsc",
"eslint": "eslint",
...
}
```

and then with call with bypassing arguments (`--`)

```bash
npm run tsc -- -w
```

**Comment by mishelen** [comment]
But want to add @dzmitrypanamarenka 

**When evaluating scripts, npm adds node_modules/.bin/ to the PATH environment variable. That means you can forego the folder prefix entirely!**

So, your approach is like overkill)) Probably it can be workaround for MS?

**Pull request merged**
